version: 2

sources:
  - name: public
    tables:
      - name: customers
      - name: employees
      - name: orders
      - name: order_details
      - name: products
      - name: shippers
      - name: suppliers     
      - name: categories 